version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 300
      runas: ec2-user